# Generated by Django 4.2.7 on 2026-05-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteentry',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
