# Generated by Django 4.2.7 on 2026-05-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteentry_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebatch',
            name='current_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
